version: 2.1
jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- Installing dependencies-----------"
            sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz
            sudo tar -xvf node-v18.0.0-linux-x64.tar.xz
            sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/
            node --version => v18.0.0
            sudo apt install nodejs
            echo "--------- The images is Building ------------"
            docker build -t observability-backend-service ./reference-app/backend
            docker tag location newthingade/observability-backend-service:v1
          
            docker build -t location_svc ./reference-app/frontend
            docker tag location_svc newthingade/observability-frontend-app:v1
            
            docker build -t api_people ./reference-app/trial
            docker tag api_people newthingade/observability-trial-service:v1

            echo "-------- All images succesfully built----------"

            echo " ------- login in to hub--------"

            docker login -u newthingade -p $DOCKERPASS

            echo "-------------- Pushing images to dockerhub-------"
            
            docker push newthingade/observability-backend-service:v1
            docker push newthingade/observability-frontend-app:v1
            docker push newthingade/observability-trial-service:v1
workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]
