version: 2.1
jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- Installing dependencies-----------"
            sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz
            sudo tar -xvf node-v18.0.0-linux-x64.tar.xz
            sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/
            node --version => v18.0.0
            sudo apt install nodejs
            
            echo "--------- The images is Building ------------"

            docker build -t observability-backend-app ./reference-app/backend
            docker tag observability-backend-app newthingade/observability-backend-app:latest
          
            docker build -t observability-frontend-app ./reference-app/frontend
            docker tag observability-frontend-app newthingade/observability-frontend-app:latest
            
            docker build -t observability-trial-app ./reference-app/trial
            docker tag observability-trial-app: newthingade/observability-trial-app:latest

            echo "-------- All images succesfully built----------"

            echo " ------- login in to hub--------"

            docker login -u newthingade -p $DOCKERPASS

            echo "-------------- Pushing images to dockerhub-------"
            
            docker push newthingade/observability-backend-app:latest
            docker push newthingade/observability-frontend-app:latest
            docker push newthingade/observability-trial-app:latest
workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]
